#!/usr/bin/env python3
"""Strict managed macOS storage, or explicitly selected portable Linux storage."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import plistlib
import shutil
import signal
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
CONFIG = ROOT / '.local/build-storage.json'
LINKS = {
    'target': 'rust-target',
    'apps/desktop/node_modules': 'npm/desktop/node_modules',
    'apps/desktop/dist': 'frontend-dist',
    'apps/desktop/src-tauri/binaries': 'tauri-binaries',
    'apps/desktop/src-tauri/gen': 'tauri-gen',
    'apps/desktop/src-tauri/permissions/autogenerated': 'tauri-permissions',
    'contracts/out': 'foundry/out',
    'contracts/cache': 'foundry/cache',
    'contracts/broadcast': 'foundry/broadcast',
    'cache': 'cache',
    'output': 'output',
    '.local/verification-workspaces': 'verification-workspaces',
}


def fail(message):
    raise RuntimeError(message)


def plist(command):
    result = subprocess.run(command, capture_output=True)
    if result.returncode:
        fail(result.stderr.decode(errors='replace').strip() or 'Storage is unavailable')
    return plistlib.loads(result.stdout)


def mounted(config):
    mount = Path(config['mount'])
    if not os.path.ismount(mount):
        fail(f'Build volume is not mounted: {mount}. Run build-storage.py mount.')
    info = plist(['/usr/sbin/diskutil', 'info', '-plist', str(mount)])
    if info.get('FilesystemType') != 'apfs' or info.get('VolumeUUID') != config['volume_uuid']:
        fail(f'Unexpected filesystem or volume at {mount}; refusing to write.')
    images = plist(['/usr/bin/hdiutil', 'info', '-plist']).get('images', [])
    if not any(Path(item.get('image-path', '')).resolve() == Path(config['image']).resolve()
               and any(e.get('mount-point') == str(mount) for e in item.get('system-entities', []))
               for item in images):
        fail('The mounted volume does not belong to the configured external image.')
    return mount


def mount_image(config):
    if not os.path.ismount(config['mount']):
        image = Path(config['image'])
        if not image.is_dir():
            fail(f'External build image is unavailable: {image}. Connect WD4000 first.')
        subprocess.run(['/usr/bin/hdiutil', 'attach', '-nobrowse', str(image)], check=True)
    return mounted(config)


def check_links(config, create=False):
    mount = mounted(config)
    for relative, destination in LINKS.items():
        link, target = ROOT / relative, mount / destination
        if create:
            target.mkdir(parents=True, exist_ok=True)
            link.parent.mkdir(parents=True, exist_ok=True)
            if not link.exists() and not link.is_symlink():
                link.symlink_to(target, target_is_directory=True)
        if not link.is_symlink() or link.resolve() != target.resolve():
            fail(f'{link} must be a symlink to {target}; refusing an internal build fallback.')
        if not target.is_dir():
            fail(f'External build directory is missing: {target}. Wait for any active clean/build '
                 'to finish, or run build-storage.py setup to recreate empty directories.')


def environment(config):
    env = os.environ.copy()
    env.update(config.get('env', {}))
    env['PATH'] = os.pathsep.join(config.get('path', []) + [env.get('PATH', '')])
    env['CARGO_TARGET_DIR'] = str(ROOT / 'target')
    env['npm_config_cache'] = str(Path(config['mount']) / 'npm/cache')
    env['AIN_BUILD_STORAGE_PROFILE'] = 'mac-apfs'
    return env


def run_directory(worktree):
    """Main checkout, or an explicitly named checkout in the managed workspaces."""
    workspaces = (ROOT / '.local/verification-workspaces').resolve()
    if worktree is None:
        # run always uses the main checkout; a caller inside a workspace would
        # silently compile and test the main sources instead of its own.
        if Path.cwd().resolve().is_relative_to(workspaces):
            fail(f'The current directory is inside {workspaces}, but run would use the main '
                 'checkout. Pass --worktree PATH before run, or run from the main checkout.')
        return ROOT
    worktree = worktree.resolve()
    if worktree == workspaces or not worktree.is_relative_to(workspaces):
        fail(f'--worktree must be a checkout inside {workspaces}: {worktree}')
    if not worktree.is_dir() or not (worktree / '.git').exists():
        fail(f'--worktree must be the root of a Git checkout: {worktree}')
    if not (worktree / 'target').resolve().is_relative_to(worktree):
        fail(f'--worktree target must stay inside the worktree: {worktree / "target"}')
    return worktree


def install(config):
    check_links(config)
    depot = Path(config['mount']) / 'npm/desktop'
    names = ['package.json', 'package-lock.json']
    for name in names:
        shutil.copyfile(ROOT / 'apps/desktop' / name, depot / name)
    before = {name: hashlib.sha256((depot / name).read_bytes()).hexdigest() for name in names}
    subprocess.run(['npm', 'ci', '--no-audit', '--no-fund'], cwd=depot,
                   env=environment(config), check=True)
    for name, digest in before.items():
        if hashlib.sha256((depot / name).read_bytes()).hexdigest() != digest:
            fail(f'npm changed {name} during locked installation.')
    check_links(config)


def portable_environment(create=False):
    if sys.platform != 'linux':
        fail('The portable-linux profile requires Linux; mac-apfs remains the default.')
    env = os.environ.copy()
    root = ROOT.resolve()
    target = root / 'target'
    for selector in ('CARGO_BUILD_TARGET', 'CARGO_BUILD_TARGET_DIR'):
        if selector in env:
            fail(f'Portable {selector} is unsupported by the host artifact paths.')
    directories = [root / relative for relative in
        ('target', 'output', 'cache', 'cache/npm', '.local/verification-workspaces')]
    # Preflight the whole layout before making even the first directory/probe.
    # An inherited Mac link (including a healthy one) is never a Linux depot.
    for directory in directories:
        ancestor = root
        for part in directory.relative_to(root).parts:
            ancestor /= part
            if ancestor.is_symlink():
                fail(f'Portable storage must use real checkout-local directories, not a link: {ancestor}')
            if ancestor.exists() and not ancestor.is_dir():
                fail(f'Portable storage path is not a directory: {ancestor}')
        if not directory.resolve().is_relative_to(root):
            fail(f'Portable storage escapes the checkout: {directory}')
    configured = Path(env.get('CARGO_TARGET_DIR', str(target)))
    configured = configured if configured.is_absolute() else root / configured
    if configured.resolve() != target.resolve():
        fail('Portable CARGO_TARGET_DIR must select this checkout target.')
    for directory in directories:
        if create:
            directory.mkdir(parents=True, exist_ok=True)
        if not directory.is_dir():
            fail(f'Portable directory is unavailable: {directory}. Run setup explicitly.')
        # Test actual write access; chmod/access guesses can be wrong on mounted
        # filesystems. The probe is removed immediately, without replacing links.
        with tempfile.TemporaryFile(dir=directory):
            pass
    env.update(CARGO_TARGET_DIR=str(target), npm_config_cache=str(root / 'cache/npm'),
        AIN_BUILD_STORAGE_PROFILE='portable-linux')
    return env


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--profile', choices=('mac-apfs', 'portable-linux'), default='mac-apfs')
    parser.add_argument('--output', type=Path, help='fresh directory for durable command/doctor evidence')
    parser.add_argument('--worktree', type=Path,
        help='run in this checkout under .local/verification-workspaces with its own target')
    parser.add_argument('action', nargs='?', default='check',
        choices=('check', 'mount', 'setup', 'install', 'run', 'unmount', 'doctor'))
    parser.add_argument('command', nargs=argparse.REMAINDER)
    args = parser.parse_args(argv)
    action = args.action
    if action == 'run' and not args.command:
        fail('A command is required after run.')
    if args.worktree is not None and (action != 'run' or args.profile != 'mac-apfs'):
        fail('--worktree is supported only by mac-apfs run.')
    if action == 'doctor' and args.profile == 'mac-apfs' and sys.platform != 'darwin':
        # Diagnose unsupported hosts before touching Mac configuration/storage.
        # Every operational action still goes through the strict profile gate.
        env = os.environ.copy()
    elif args.profile == 'portable-linux':
        if action not in {'check', 'setup', 'run', 'doctor'}:
            fail(f'{action} is unsupported by portable-linux; no image or installer is used.')
        env = portable_environment(create=action in {'setup', 'run', 'doctor'})
    else:
        env = managed_action(action)
    cwd = ROOT
    if action == 'run' and args.profile == 'mac-apfs':
        # Validated only after the volume, image and managed links.
        cwd = run_directory(args.worktree)
        env['CARGO_TARGET_DIR'] = str(cwd / 'target')
    if action == 'doctor':
        from build_evidence import doctor, write_json
        options = argparse.ArgumentParser(prog='build-storage.py doctor')
        options.add_argument('--suite', required=True)
        options.add_argument('--phase', choices=('build', 'runtime'), default='build')
        selection = options.parse_args(args.command)
        report = doctor(ROOT, selection.suite, profile=args.profile, env=env, phase=selection.phase)
        if args.output:
            if (args.output / 'check.json').exists():
                fail(f'Evidence already exists: {args.output}')
            write_json(args.output / 'check.json', report)
        print(json.dumps(report, indent=2))
        return 0 if report['status'] == 'passed' else 2
    if action == 'run':
        command = args.command[1:] if args.command[:1] == ['--'] else args.command
        if not command:
            fail('A command is required after run.')
        if args.output:
            from build_evidence import run_command, write_json
            if (args.output / 'check.json').exists():
                fail(f'Evidence already exists: {args.output}')
            report = dict(status='running', passed=False, commands=[])
            write_json(args.output / 'check.json', report)
            try:
                run_command('command', command, report, output=args.output, cwd=cwd, env=env)
                report.update(status='passed', passed=True)
            except BaseException:
                report.update(status='failed', passed=False)
                raise
            finally:
                write_json(args.output / 'check.json', report)
        else:
            previous = Path.cwd()
            try:
                os.chdir(cwd)
                os.execvpe(command[0], command, env)
            finally:
                # exec replaces the process; restoration applies only to a
                # failed exec or a fixture intercepting it.
                os.chdir(previous)
    return 0


def managed_action(action):
    if not CONFIG.exists():
        fail(f'Configure {CONFIG} before using managed external storage.')
    if sys.platform != 'darwin':
        fail('mac-apfs requires macOS. Select --profile portable-linux explicitly on Linux.')
    config = json.loads(CONFIG.read_text())
    if action in {'mount', 'setup', 'install', 'run'}:
        mount_image(config)
    if action == 'setup':
        check_links(config, create=True)
    elif action == 'install':
        install(config)
    elif action in {'run', 'doctor'}:
        check_links(config)
    elif action == 'unmount':
        mounted(config)
        # No force: an active build or open file must prevent detach.
        subprocess.run(['/usr/bin/hdiutil', 'detach', config['mount']], check=True)
    elif action == 'check':
        check_links(config)
    return environment(config)


if __name__ == '__main__':
    def terminate(signum, frame):
        raise InterruptedError(f'build wrapper received signal {signum}')
    if os.name == 'posix':
        signal.signal(signal.SIGTERM, terminate)
    try:
        sys.exit(main())
    except (RuntimeError, OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f'Build storage: {error}', file=sys.stderr)
        sys.exit(error.returncode if isinstance(error, subprocess.CalledProcessError) else 1)
