[package]
name = "agentic-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
[dependencies]
agentic-mailbox-swarm = { path = "../mailbox-swarm" }
agentic-grant-book = { path = "../grant-book" }
agentic-protocol = {path="../protocol-types"}
agentic-store = {path="../store"}
agentic-crypto = {path="../crypto"}
agentic-capabilities = {path="../capabilities"}
minicbor.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
getrandom.workspace = true
thiserror.workspace = true
ed25519-dalek.workspace = true
zeroize.workspace = true
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
hkdf = "0.13.0"
chacha20poly1305 = "0.10.1"
[dev-dependencies]
tempfile.workspace = true
rusqlite.workspace = true
[lints]
workspace = true
